/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        arena: {
          black: '#09090b',
          dark: '#0f0f11',
          darker: '#060608',
          red: '#ff2d55',
          fire: '#ff6b35',
          yellow: '#facc15',
          neon: '#39ff14',
          purple: '#a855f7',
          cyan: '#22d3ee',
          blue: '#3b82f6',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      backgroundImage: {
        'arena-gradient': 'linear-gradient(135deg, #09090b 0%, #1a0a2e 50%, #09090b 100%)',
        'fire-gradient': 'linear-gradient(135deg, #ff2d55, #ff6b35, #facc15)',
        'neon-gradient': 'linear-gradient(135deg, #a855f7, #22d3ee)',
        'damage-gradient': 'radial-gradient(circle, transparent 40%, rgba(255,45,85,0.3) 100%)',
      },
      boxShadow: {
        'neon-yellow': '0 0 20px rgba(250,204,21,0.3), 0 0 40px rgba(250,204,21,0.1)',
        'neon-red': '0 0 20px rgba(255,45,85,0.3), 0 0 40px rgba(255,45,85,0.1)',
        'neon-cyan': '0 0 20px rgba(34,211,238,0.3), 0 0 40px rgba(34,211,238,0.1)',
        'neon-purple': '0 0 20px rgba(168,85,247,0.3), 0 0 40px rgba(168,85,247,0.1)',
        'neon-green': '0 0 20px rgba(57,255,20,0.3), 0 0 40px rgba(57,255,20,0.1)',
        'arena-glow': '0 0 60px rgba(250,204,21,0.15), inset 0 0 60px rgba(250,204,21,0.05)',
      },
      animation: {
        'shake-light': 'shake-light 0.3s ease-in-out',
        'shake-medium': 'shake-medium 0.4s ease-in-out',
        'shake-heavy': 'shake-heavy 0.6s ease-in-out',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'pulse-fast': 'pulse-glow 0.8s ease-in-out infinite',
        'glitch': 'glitch 0.3s ease-in-out',
        'glitch-loop': 'glitch 2s infinite',
        'damage-flash': 'damage-flash 0.4s ease-out',
        'slide-up': 'slide-up 0.4s ease-out',
        'slide-down': 'slide-down 0.3s ease-out',
        'slide-left': 'slide-left 0.3s ease-out',
        'slide-right': 'slide-right 0.3s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'typing-pulse': 'typing-pulse 1.5s ease-in-out infinite',
        'countdown-pop': 'countdown-pop 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'scale-in': 'scale-in 0.3s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'fire-border': 'fire-border 2s linear infinite',
        'spin-slow': 'spin 8s linear infinite',
        'bounce-in': 'bounce-in 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
      keyframes: {
        'shake-light': {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-2px)' },
          '75%': { transform: 'translateX(2px)' },
        },
        'shake-medium': {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%': { transform: 'translateX(-4px) rotate(-0.5deg)' },
          '30%': { transform: 'translateX(4px) rotate(0.5deg)' },
          '50%': { transform: 'translateX(-3px) rotate(-0.3deg)' },
          '70%': { transform: 'translateX(3px) rotate(0.3deg)' },
          '90%': { transform: 'translateX(-1px)' },
        },
        'shake-heavy': {
          '0%, 100%': { transform: 'translateX(0) rotate(0)' },
          '10%': { transform: 'translateX(-8px) rotate(-1deg)' },
          '20%': { transform: 'translateX(8px) rotate(1deg)' },
          '30%': { transform: 'translateX(-6px) rotate(-0.8deg)' },
          '40%': { transform: 'translateX(6px) rotate(0.8deg)' },
          '50%': { transform: 'translateX(-4px) rotate(-0.5deg)' },
          '60%': { transform: 'translateX(4px) rotate(0.5deg)' },
          '70%': { transform: 'translateX(-2px)' },
          '80%': { transform: 'translateX(2px)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'glitch': {
          '0%': { transform: 'translate(0)', filter: 'hue-rotate(0deg)' },
          '10%': { transform: 'translate(-2px, 2px)', filter: 'hue-rotate(90deg)' },
          '20%': { transform: 'translate(2px, -2px)', filter: 'hue-rotate(180deg)' },
          '30%': { transform: 'translate(-1px, -1px)', filter: 'hue-rotate(270deg)' },
          '40%': { transform: 'translate(1px, 2px)', filter: 'hue-rotate(360deg)' },
          '50%': { transform: 'translate(-2px, 1px)', filter: 'hue-rotate(0deg)' },
          '60%': { transform: 'translate(2px, 1px)' },
          '70%': { transform: 'translate(-1px, -2px)' },
          '80%': { transform: 'translate(1px, 1px)' },
          '100%': { transform: 'translate(0)', filter: 'hue-rotate(0deg)' },
        },
        'damage-flash': {
          '0%': { opacity: '0.8', background: 'rgba(255,45,85,0.4)' },
          '100%': { opacity: '0', background: 'rgba(255,45,85,0)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-left': {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-right': {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'typing-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '1' },
        },
        'countdown-pop': {
          '0%': { transform: 'scale(3)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '0' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fire-border': {
          '0%': { borderColor: '#ff2d55' },
          '33%': { borderColor: '#ff6b35' },
          '66%': { borderColor: '#facc15' },
          '100%': { borderColor: '#ff2d55' },
        },
        'bounce-in': {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '60%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};